// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/model_node_mode.proto

package simulator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenderRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderRegistry map[string]*SenderMode `protobuf:"bytes,1,rep,name=sender_registry,json=senderRegistry,proto3" json:"sender_registry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SenderRegistry) Reset() {
	*x = SenderRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_node_mode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderRegistry) ProtoMessage() {}

func (x *SenderRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_node_mode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderRegistry.ProtoReflect.Descriptor instead.
func (*SenderRegistry) Descriptor() ([]byte, []int) {
	return file_proto_model_node_mode_proto_rawDescGZIP(), []int{0}
}

func (x *SenderRegistry) GetSenderRegistry() map[string]*SenderMode {
	if x != nil {
		return x.SenderRegistry
	}
	return nil
}

type ReceiverRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverRegistry map[string]string `protobuf:"bytes,1,rep,name=receiver_registry,json=receiverRegistry,proto3" json:"receiver_registry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReceiverRegistry) Reset() {
	*x = ReceiverRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_node_mode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiverRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverRegistry) ProtoMessage() {}

func (x *ReceiverRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_node_mode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverRegistry.ProtoReflect.Descriptor instead.
func (*ReceiverRegistry) Descriptor() ([]byte, []int) {
	return file_proto_model_node_mode_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiverRegistry) GetReceiverRegistry() map[string]string {
	if x != nil {
		return x.ReceiverRegistry
	}
	return nil
}

type SenderMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId              string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IntervalMillisecond uint32 `protobuf:"varint,2,opt,name=interval_millisecond,json=intervalMillisecond,proto3" json:"interval_millisecond,omitempty"`
}

func (x *SenderMode) Reset() {
	*x = SenderMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_node_mode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderMode) ProtoMessage() {}

func (x *SenderMode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_node_mode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderMode.ProtoReflect.Descriptor instead.
func (*SenderMode) Descriptor() ([]byte, []int) {
	return file_proto_model_node_mode_proto_rawDescGZIP(), []int{2}
}

func (x *SenderMode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SenderMode) GetIntervalMillisecond() uint32 {
	if x != nil {
		return x.IntervalMillisecond
	}
	return 0
}

var File_proto_model_node_mode_proto protoreflect.FileDescriptor

var file_proto_model_node_mode_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xc2, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x56, 0x0a, 0x0f, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x1a, 0x58, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x69,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb7, 0x01,
	0x0a, 0x10, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x12, 0x5e, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x79, 0x1a, 0x43, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x31,
	0x0a, 0x14, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x73, 0x69, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_node_mode_proto_rawDescOnce sync.Once
	file_proto_model_node_mode_proto_rawDescData = file_proto_model_node_mode_proto_rawDesc
)

func file_proto_model_node_mode_proto_rawDescGZIP() []byte {
	file_proto_model_node_mode_proto_rawDescOnce.Do(func() {
		file_proto_model_node_mode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_node_mode_proto_rawDescData)
	})
	return file_proto_model_node_mode_proto_rawDescData
}

var file_proto_model_node_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_model_node_mode_proto_goTypes = []interface{}{
	(*SenderRegistry)(nil),   // 0: simulator.SenderRegistry
	(*ReceiverRegistry)(nil), // 1: simulator.ReceiverRegistry
	(*SenderMode)(nil),       // 2: simulator.SenderMode
	nil,                      // 3: simulator.SenderRegistry.SenderRegistryEntry
	nil,                      // 4: simulator.ReceiverRegistry.ReceiverRegistryEntry
}
var file_proto_model_node_mode_proto_depIdxs = []int32{
	3, // 0: simulator.SenderRegistry.sender_registry:type_name -> simulator.SenderRegistry.SenderRegistryEntry
	4, // 1: simulator.ReceiverRegistry.receiver_registry:type_name -> simulator.ReceiverRegistry.ReceiverRegistryEntry
	2, // 2: simulator.SenderRegistry.SenderRegistryEntry.value:type_name -> simulator.SenderMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_model_node_mode_proto_init() }
func file_proto_model_node_mode_proto_init() {
	if File_proto_model_node_mode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_node_mode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_node_mode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiverRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_node_mode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_node_mode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_node_mode_proto_goTypes,
		DependencyIndexes: file_proto_model_node_mode_proto_depIdxs,
		MessageInfos:      file_proto_model_node_mode_proto_msgTypes,
	}.Build()
	File_proto_model_node_mode_proto = out.File
	file_proto_model_node_mode_proto_rawDesc = nil
	file_proto_model_node_mode_proto_goTypes = nil
	file_proto_model_node_mode_proto_depIdxs = nil
}
